"""nullable amount column for entries

Revision ID: 08ee0011efc1
Revises: 4788932b1fde
Create Date: 2021-01-02 04:40:12.219683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ee0011efc1'
down_revision = '4788932b1fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
