"""created user model but imported into main models.py this time

Revision ID: 09d5d3f71cf4
Revises: a5ee42f3cea7
Create Date: 2021-01-09 21:29:04.659030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d5d3f71cf4'
down_revision = 'a5ee42f3cea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
