"""set goal name to unique

Revision ID: 8040cec689c3
Revises: ec4b1d088165
Create Date: 2021-01-01 23:59:00.948125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8040cec689c3'
down_revision = 'ec4b1d088165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'goals', ['goal'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goals', type_='unique')
    # ### end Alembic commands ###
