"""created user model

Revision ID: a5ee42f3cea7
Revises: e74329689b23
Create Date: 2021-01-09 21:27:26.887222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ee42f3cea7'
down_revision = 'e74329689b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
