"""import user model metadata into alembic

Revision ID: aaa8141c13b6
Revises: 09d5d3f71cf4
Create Date: 2021-01-09 21:31:53.065966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa8141c13b6'
down_revision = '09d5d3f71cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
