"""passing User model thru user relationship)


Revision ID: e9ac74c2fb4f
Revises: 2171019a778e
Create Date: 2021-01-09 22:57:55.812261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ac74c2fb4f'
down_revision = '2171019a778e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
