"""added date created to goal

Revision ID: ec4b1d088165
Revises: 40af0cb3caab
Create Date: 2021-01-01 23:13:56.890657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4b1d088165'
down_revision = '40af0cb3caab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('date_created', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'date_created')
    # ### end Alembic commands ###
