version: '3'

services:
  # streamlit:
  #   volumes:
  #     - ./streamlit/:/streamlit/
  #   build:
  #     context: ./streamlit
  #     dockerfile: Dockerfile
  #   container_name: streamlit
  #   restart: always
  #   # do not publicly expose port 8501
  #   # ports:
  #   #   - "8501:8501"
  #   depends_on:
  #     - api
  #   networks:
  #     - app-network
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - reverse
    command: certonly --webroot --webroot-path=/var/www/html --email edwardsapp@gmail.com --agree-tos --no-eff-email -d flip.rip  -d www.flip.rip
  
  reverse:
    container_name: reverse
    hostname: reverse
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pgadmin4
      - svelte
      # - streamlit
      - postgres
      - api
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - dhparam:/etc/ssl/certs
    networks:
      - app-network
    
  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # ports:
    #   - "5432:5432"
    env_file:
      - ./postgres/.env
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/:/api/
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    # ports:
    #   - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network
    
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    env_file:
      - ./pgadmin4/.env
    # ports: 
    #   - "5050:80"
    depends_on:
      - postgres
    logging:
      driver: none
    networks:
      - app-network
  
  svelte:
    build: ./svelte
    command: npm run dev
    volumes:
      - ./svelte/:/svelte/
    networks:
      - app-network
    
volumes:
  postgres_data:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ed/flip/svelte/public
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ed/flip/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge